### PR TITLE
Fix encoding issues for utf-16

### PR DESCRIPTION
**Pull request by steciuk**
I was happily using your lib (thanks!), but run into some issues with subs encoding. After some tests, it looked like it usually has problems with utf-16.
- I quickly duct-taped a solution (cbba6a8b4b9cc7693d387561e9fa6ea36aee5a63),
- and added `chardet` auto encoding detection just to be sure (4b5009e2749107f424491bfee6a1ee0a4e1733c6).

I've never used Poetry or published a python package, so I would be glad If you could properly complete this PR and hopefully update `napi-py` <3.

### CODE REVIEW

**Comment by emkor** [comment]
Thanks for activity on the project and fixing the issue, will review sometime next week as I'm pretty busy right now

**Comment by steciuk** [comment]
Sure!
I've decided to watch some Poetry 101 on YT and updated the deps to make it easier on you. When you have some time to review, please let me know if there is anything else that should be done.

**Review by emkor — APPROVED** [review]
looks good

**Comment by emkor** [comment]
Newest version has been released to pypi https://pypi.org/project/napi-py/1.2.3/
thanks for contributing

**Pull request merged**
